// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVZyO3wEhzw5isj7Wn2hL596SIEmEYzdI',
    appId: '1:473171371428:web:2a4be596a0e58467d74d31',
    messagingSenderId: '473171371428',
    projectId: 'e-commerce-20f2f',
    authDomain: 'e-commerce-20f2f.firebaseapp.com',
    storageBucket: 'e-commerce-20f2f.appspot.com',
    measurementId: 'G-HG1H8WBP80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn5Q5utsSqdvdYDxQyh5RjtvHynV9rS4U',
    appId: '1:473171371428:android:3d87b924e823a1f8d74d31',
    messagingSenderId: '473171371428',
    projectId: 'e-commerce-20f2f',
    storageBucket: 'e-commerce-20f2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANeGClJHn9zBhfG26oQbZCX7B1_coqsd4',
    appId: '1:473171371428:ios:50ec961a8f35bca2d74d31',
    messagingSenderId: '473171371428',
    projectId: 'e-commerce-20f2f',
    storageBucket: 'e-commerce-20f2f.appspot.com',
    iosBundleId: 'com.example.macstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANeGClJHn9zBhfG26oQbZCX7B1_coqsd4',
    appId: '1:473171371428:ios:50ec961a8f35bca2d74d31',
    messagingSenderId: '473171371428',
    projectId: 'e-commerce-20f2f',
    storageBucket: 'e-commerce-20f2f.appspot.com',
    iosBundleId: 'com.example.macstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVZyO3wEhzw5isj7Wn2hL596SIEmEYzdI',
    appId: '1:473171371428:web:a866a8aacc32c089d74d31',
    messagingSenderId: '473171371428',
    projectId: 'e-commerce-20f2f',
    authDomain: 'e-commerce-20f2f.firebaseapp.com',
    storageBucket: 'e-commerce-20f2f.appspot.com',
    measurementId: 'G-G6HDJ260HZ',
  );
}
